// ============================================================
// Summer Goals — learning content
// French vocab format: f = French, e = English, w = week (1-4), c = category
// ============================================================
const APP_DATA = {

plan: {
  month: "2026-08",
  weeks: [
    { n: 1, title: "Sounds & survival", fr: "Language Transfer 1–12 · pronunciation · greetings · numbers · être/avoir/aller/faire · question words", asl: "Lifeprint 1–4 · alphabet until automatic · numbers 1–30 · greetings" },
    { n: 2, title: "Building sentences", fr: "Language Transfer 13–26 · regular verbs · articles & gender · adjectives · near future · start Easy French videos", asl: "Lifeprint 5–9 · family · feelings · everyday verbs · topic-comment order · facial grammar" },
    { n: 3, title: "Past tense & real conversation", fr: "Language Transfer 27–40 · passé composé · daily journal in French · voice messages with partners", asl: "Lifeprint 10–14 · time signs · calendar · daily routine · practice sentences at speed" },
    { n: 4, title: "Consolidation & A2 push", fr: "No new grammar · drill weak spots · TV5Monde A2 exercises · opinions · mock speaking exams", asl: "Lifeprint 15–18 · review all vocab · watch Deaf creators and count what you catch" }
  ],
  dailyTasks: [
    { id: "lt",   label: "Language Transfer (45 min)", icon: "🎧" },
    { id: "srs",  label: "Flashcards — clear your reviews (25 min)", icon: "🃏" },
    { id: "conv", label: "Conversation practice with Claude (30 min)", icon: "💬" },
    { id: "input",label: "French input — TV5Monde / Easy French (20 min)", icon: "📺" },
    { id: "asl",  label: "ASL — Lifeprint lesson + fingerspelling (45 min)", icon: "🤟" }
  ],
  milestones: [
    { date: "2026-08-07", text: "60-second self-introduction in French · fingerspell anything smoothly (slow speed)" },
    { date: "2026-08-14", text: "Order a meal + full 'where are you from / what do you do' exchange · sign a 5-sentence ASL self-intro" },
    { date: "2026-08-21", text: "Narrate your yesterday in ~10 French sentences (passé composé) · 2-minute signed exchange about your week" },
    { date: "2026-08-31", text: "5-minute spontaneous French conversation (past/present/future) · comfortable basic ASL dialogue" }
  ]
},

french: {
vocab: [
// ---------- WEEK 1: greetings, basics, numbers, core verbs, questions ----------
{f:"bonjour",e:"hello / good day",w:1,c:"greetings"},
{f:"bonsoir",e:"good evening",w:1,c:"greetings"},
{f:"salut",e:"hi / bye (casual)",w:1,c:"greetings"},
{f:"au revoir",e:"goodbye",w:1,c:"greetings"},
{f:"à bientôt",e:"see you soon",w:1,c:"greetings"},
{f:"à demain",e:"see you tomorrow",w:1,c:"greetings"},
{f:"bonne nuit",e:"good night",w:1,c:"greetings"},
{f:"s'il vous plaît",e:"please (formal)",w:1,c:"greetings"},
{f:"s'il te plaît",e:"please (informal)",w:1,c:"greetings"},
{f:"merci beaucoup",e:"thank you very much",w:1,c:"greetings"},
{f:"de rien",e:"you're welcome",w:1,c:"greetings"},
{f:"excusez-moi",e:"excuse me",w:1,c:"greetings"},
{f:"pardon",e:"sorry / pardon",w:1,c:"greetings"},
{f:"oui",e:"yes",w:1,c:"basics"},
{f:"non",e:"no",w:1,c:"basics"},
{f:"peut-être",e:"maybe",w:1,c:"basics"},
{f:"d'accord",e:"okay / agreed",w:1,c:"basics"},
{f:"ça va ?",e:"how's it going?",w:1,c:"greetings"},
{f:"ça va bien",e:"it's going well",w:1,c:"greetings"},
{f:"comment allez-vous ?",e:"how are you? (formal)",w:1,c:"greetings"},
{f:"je m'appelle…",e:"my name is…",w:1,c:"intro"},
{f:"comment tu t'appelles ?",e:"what's your name?",w:1,c:"intro"},
{f:"enchanté",e:"nice to meet you",w:1,c:"intro"},
{f:"je viens de…",e:"I come from…",w:1,c:"intro"},
{f:"j'habite à…",e:"I live in…",w:1,c:"intro"},
{f:"je suis étudiant",e:"I am a student (m.)",w:1,c:"intro"},
{f:"je parle un peu français",e:"I speak a little French",w:1,c:"intro"},
{f:"je ne comprends pas",e:"I don't understand",w:1,c:"survival"},
{f:"pouvez-vous répéter ?",e:"can you repeat?",w:1,c:"survival"},
{f:"plus lentement",e:"more slowly",w:1,c:"survival"},
{f:"comment dit-on… ?",e:"how do you say…?",w:1,c:"survival"},
{f:"qu'est-ce que ça veut dire ?",e:"what does that mean?",w:1,c:"survival"},
{f:"je ne sais pas",e:"I don't know",w:1,c:"survival"},
{f:"être",e:"to be",w:1,c:"verbs"},
{f:"je suis",e:"I am",w:1,c:"verbs"},
{f:"tu es",e:"you are (informal)",w:1,c:"verbs"},
{f:"il est / elle est",e:"he is / she is",w:1,c:"verbs"},
{f:"nous sommes",e:"we are",w:1,c:"verbs"},
{f:"vous êtes",e:"you are (formal/plural)",w:1,c:"verbs"},
{f:"ils sont",e:"they are",w:1,c:"verbs"},
{f:"avoir",e:"to have",w:1,c:"verbs"},
{f:"j'ai",e:"I have",w:1,c:"verbs"},
{f:"tu as",e:"you have",w:1,c:"verbs"},
{f:"il a / elle a",e:"he has / she has",w:1,c:"verbs"},
{f:"nous avons",e:"we have",w:1,c:"verbs"},
{f:"vous avez",e:"you have (formal/plural)",w:1,c:"verbs"},
{f:"ils ont",e:"they have",w:1,c:"verbs"},
{f:"aller",e:"to go",w:1,c:"verbs"},
{f:"je vais",e:"I go / I am going",w:1,c:"verbs"},
{f:"tu vas",e:"you go",w:1,c:"verbs"},
{f:"il va",e:"he goes",w:1,c:"verbs"},
{f:"nous allons",e:"we go",w:1,c:"verbs"},
{f:"faire",e:"to do / to make",w:1,c:"verbs"},
{f:"je fais",e:"I do / I make",w:1,c:"verbs"},
{f:"tu fais",e:"you do",w:1,c:"verbs"},
{f:"il fait",e:"he does / it makes",w:1,c:"verbs"},
{f:"qui",e:"who",w:1,c:"questions"},
{f:"quoi",e:"what",w:1,c:"questions"},
{f:"où",e:"where",w:1,c:"questions"},
{f:"quand",e:"when",w:1,c:"questions"},
{f:"pourquoi",e:"why",w:1,c:"questions"},
{f:"comment",e:"how",w:1,c:"questions"},
{f:"combien",e:"how much / how many",w:1,c:"questions"},
{f:"qu'est-ce que…",e:"what… (question starter)",w:1,c:"questions"},
{f:"est-ce que…",e:"(turns a statement into a question)",w:1,c:"questions"},
{f:"parce que",e:"because",w:1,c:"basics"},
{f:"un / une",e:"a, an (m. / f.)",w:1,c:"basics"},
{f:"le / la / les",e:"the (m. / f. / plural)",w:1,c:"basics"},
{f:"et",e:"and",w:1,c:"basics"},
{f:"ou",e:"or",w:1,c:"basics"},
{f:"mais",e:"but",w:1,c:"basics"},
{f:"avec",e:"with",w:1,c:"basics"},
{f:"sans",e:"without",w:1,c:"basics"},
{f:"pour",e:"for",w:1,c:"basics"},
{f:"dans",e:"in / inside",w:1,c:"basics"},
{f:"sur",e:"on",w:1,c:"basics"},
{f:"sous",e:"under",w:1,c:"basics"},
{f:"ici",e:"here",w:1,c:"basics"},
{f:"là-bas",e:"over there",w:1,c:"basics"},
{f:"aussi",e:"also / too",w:1,c:"basics"},
{f:"très",e:"very",w:1,c:"basics"},
{f:"un peu",e:"a little",w:1,c:"basics"},
{f:"beaucoup",e:"a lot",w:1,c:"basics"},
{f:"zéro",e:"zero",w:1,c:"numbers"},
{f:"un, deux, trois",e:"one, two, three",w:1,c:"numbers"},
{f:"quatre, cinq, six",e:"four, five, six",w:1,c:"numbers"},
{f:"sept, huit, neuf",e:"seven, eight, nine",w:1,c:"numbers"},
{f:"dix",e:"ten",w:1,c:"numbers"},
{f:"onze, douze, treize",e:"eleven, twelve, thirteen",w:1,c:"numbers"},
{f:"quatorze, quinze, seize",e:"fourteen, fifteen, sixteen",w:1,c:"numbers"},
{f:"dix-sept, dix-huit, dix-neuf",e:"seventeen, eighteen, nineteen",w:1,c:"numbers"},
{f:"vingt",e:"twenty",w:1,c:"numbers"},
{f:"trente",e:"thirty",w:1,c:"numbers"},
{f:"quarante",e:"forty",w:1,c:"numbers"},
{f:"cinquante",e:"fifty",w:1,c:"numbers"},
{f:"soixante",e:"sixty",w:1,c:"numbers"},
{f:"soixante-dix",e:"seventy",w:1,c:"numbers"},
{f:"quatre-vingts",e:"eighty",w:1,c:"numbers"},
{f:"quatre-vingt-dix",e:"ninety",w:1,c:"numbers"},
{f:"cent",e:"one hundred",w:1,c:"numbers"},
{f:"l'homme",e:"the man",w:1,c:"people"},
{f:"la femme",e:"the woman",w:1,c:"people"},
{f:"le garçon",e:"the boy",w:1,c:"people"},
{f:"la fille",e:"the girl / daughter",w:1,c:"people"},
{f:"l'ami / l'amie",e:"the friend (m. / f.)",w:1,c:"people"},
{f:"les gens",e:"people",w:1,c:"people"},
{f:"aujourd'hui",e:"today",w:1,c:"time"},
{f:"demain",e:"tomorrow",w:1,c:"time"},
{f:"hier",e:"yesterday",w:1,c:"time"},
{f:"maintenant",e:"now",w:1,c:"time"},
{f:"le matin",e:"the morning",w:1,c:"time"},
{f:"l'après-midi",e:"the afternoon",w:1,c:"time"},
{f:"le soir",e:"the evening",w:1,c:"time"},
{f:"la nuit",e:"the night",w:1,c:"time"},
{f:"le jour",e:"the day",w:1,c:"time"},
{f:"la semaine",e:"the week",w:1,c:"time"},

// ---------- WEEK 2: food, family, adjectives, places, -er verbs ----------
{f:"manger",e:"to eat",w:2,c:"verbs"},
{f:"boire",e:"to drink",w:2,c:"verbs"},
{f:"parler",e:"to speak",w:2,c:"verbs"},
{f:"habiter",e:"to live (somewhere)",w:2,c:"verbs"},
{f:"travailler",e:"to work",w:2,c:"verbs"},
{f:"étudier",e:"to study",w:2,c:"verbs"},
{f:"aimer",e:"to like / to love",w:2,c:"verbs"},
{f:"adorer",e:"to adore / love",w:2,c:"verbs"},
{f:"détester",e:"to hate",w:2,c:"verbs"},
{f:"vouloir",e:"to want",w:2,c:"verbs"},
{f:"je voudrais…",e:"I would like… (polite)",w:2,c:"verbs"},
{f:"pouvoir",e:"to be able to / can",w:2,c:"verbs"},
{f:"je peux",e:"I can",w:2,c:"verbs"},
{f:"devoir",e:"to have to / must",w:2,c:"verbs"},
{f:"je dois",e:"I must",w:2,c:"verbs"},
{f:"acheter",e:"to buy",w:2,c:"verbs"},
{f:"chercher",e:"to look for",w:2,c:"verbs"},
{f:"trouver",e:"to find",w:2,c:"verbs"},
{f:"donner",e:"to give",w:2,c:"verbs"},
{f:"prendre",e:"to take",w:2,c:"verbs"},
{f:"je prends",e:"I take / I'll have",w:2,c:"verbs"},
{f:"regarder",e:"to watch / to look at",w:2,c:"verbs"},
{f:"écouter",e:"to listen to",w:2,c:"verbs"},
{f:"jouer",e:"to play",w:2,c:"verbs"},
{f:"il y a",e:"there is / there are",w:2,c:"grammar"},
{f:"je vais + infinitif",e:"I'm going to… (near future)",w:2,c:"grammar"},
{f:"ne… pas",e:"not (negation sandwich)",w:2,c:"grammar"},
{f:"le pain",e:"the bread",w:2,c:"food"},
{f:"l'eau",e:"the water",w:2,c:"food"},
{f:"le café",e:"the coffee",w:2,c:"food"},
{f:"le thé",e:"the tea",w:2,c:"food"},
{f:"le lait",e:"the milk",w:2,c:"food"},
{f:"le fromage",e:"the cheese",w:2,c:"food"},
{f:"la viande",e:"the meat",w:2,c:"food"},
{f:"le poulet",e:"the chicken",w:2,c:"food"},
{f:"le poisson",e:"the fish",w:2,c:"food"},
{f:"les légumes",e:"the vegetables",w:2,c:"food"},
{f:"les fruits",e:"the fruits",w:2,c:"food"},
{f:"la pomme",e:"the apple",w:2,c:"food"},
{f:"le riz",e:"the rice",w:2,c:"food"},
{f:"l'œuf",e:"the egg",w:2,c:"food"},
{f:"le petit-déjeuner",e:"breakfast",w:2,c:"food"},
{f:"le déjeuner",e:"lunch",w:2,c:"food"},
{f:"le dîner",e:"dinner",w:2,c:"food"},
{f:"l'addition, s'il vous plaît",e:"the bill, please",w:2,c:"food"},
{f:"c'est délicieux",e:"it's delicious",w:2,c:"food"},
{f:"j'ai faim",e:"I'm hungry",w:2,c:"food"},
{f:"j'ai soif",e:"I'm thirsty",w:2,c:"food"},
{f:"la famille",e:"the family",w:2,c:"family"},
{f:"le père",e:"the father",w:2,c:"family"},
{f:"la mère",e:"the mother",w:2,c:"family"},
{f:"le frère",e:"the brother",w:2,c:"family"},
{f:"la sœur",e:"the sister",w:2,c:"family"},
{f:"le fils",e:"the son",w:2,c:"family"},
{f:"les parents",e:"the parents",w:2,c:"family"},
{f:"les enfants",e:"the children",w:2,c:"family"},
{f:"le mari",e:"the husband",w:2,c:"family"},
{f:"grand / grande",e:"big, tall (m. / f.)",w:2,c:"adjectives"},
{f:"petit / petite",e:"small (m. / f.)",w:2,c:"adjectives"},
{f:"bon / bonne",e:"good (m. / f.)",w:2,c:"adjectives"},
{f:"mauvais / mauvaise",e:"bad (m. / f.)",w:2,c:"adjectives"},
{f:"beau / belle",e:"beautiful (m. / f.)",w:2,c:"adjectives"},
{f:"nouveau / nouvelle",e:"new (m. / f.)",w:2,c:"adjectives"},
{f:"vieux / vieille",e:"old (m. / f.)",w:2,c:"adjectives"},
{f:"jeune",e:"young",w:2,c:"adjectives"},
{f:"facile",e:"easy",w:2,c:"adjectives"},
{f:"difficile",e:"difficult",w:2,c:"adjectives"},
{f:"cher / chère",e:"expensive; dear",w:2,c:"adjectives"},
{f:"content / contente",e:"happy, glad",w:2,c:"adjectives"},
{f:"fatigué / fatiguée",e:"tired",w:2,c:"adjectives"},
{f:"intéressant",e:"interesting",w:2,c:"adjectives"},
{f:"la maison",e:"the house",w:2,c:"places"},
{f:"l'appartement",e:"the apartment",w:2,c:"places"},
{f:"la ville",e:"the city",w:2,c:"places"},
{f:"la rue",e:"the street",w:2,c:"places"},
{f:"le magasin",e:"the shop",w:2,c:"places"},
{f:"le marché",e:"the market",w:2,c:"places"},
{f:"le restaurant",e:"the restaurant",w:2,c:"places"},
{f:"l'école",e:"the school",w:2,c:"places"},
{f:"la gare",e:"the train station",w:2,c:"places"},
{f:"l'aéroport",e:"the airport",w:2,c:"places"},
{f:"l'hôpital",e:"the hospital",w:2,c:"places"},
{f:"la banque",e:"the bank",w:2,c:"places"},
{f:"à gauche",e:"to the left",w:2,c:"directions"},
{f:"à droite",e:"to the right",w:2,c:"directions"},
{f:"tout droit",e:"straight ahead",w:2,c:"directions"},
{f:"près de",e:"near",w:2,c:"directions"},
{f:"loin de",e:"far from",w:2,c:"directions"},
{f:"où est… ?",e:"where is…?",w:2,c:"directions"},
{f:"ça coûte combien ?",e:"how much does it cost?",w:2,c:"shopping"},
{f:"c'est trop cher",e:"it's too expensive",w:2,c:"shopping"},
{f:"l'argent",e:"the money",w:2,c:"shopping"},
{f:"lundi",e:"Monday",w:2,c:"time"},
{f:"mardi",e:"Tuesday",w:2,c:"time"},
{f:"mercredi",e:"Wednesday",w:2,c:"time"},
{f:"jeudi",e:"Thursday",w:2,c:"time"},
{f:"vendredi",e:"Friday",w:2,c:"time"},
{f:"samedi",e:"Saturday",w:2,c:"time"},
{f:"dimanche",e:"Sunday",w:2,c:"time"},
{f:"le week-end",e:"the weekend",w:2,c:"time"},
{f:"quelle heure est-il ?",e:"what time is it?",w:2,c:"time"},
{f:"il est trois heures",e:"it is three o'clock",w:2,c:"time"},

// ---------- WEEK 3: passé composé, daily routine, weather, body/health ----------
{f:"j'ai mangé",e:"I ate (passé composé)",w:3,c:"past"},
{f:"j'ai parlé",e:"I spoke",w:3,c:"past"},
{f:"j'ai fait",e:"I did / I made",w:3,c:"past"},
{f:"j'ai vu",e:"I saw",w:3,c:"past"},
{f:"j'ai pris",e:"I took",w:3,c:"past"},
{f:"j'ai eu",e:"I had",w:3,c:"past"},
{f:"j'ai été",e:"I was",w:3,c:"past"},
{f:"je suis allé(e)",e:"I went (être verb!)",w:3,c:"past"},
{f:"je suis arrivé(e)",e:"I arrived",w:3,c:"past"},
{f:"je suis parti(e)",e:"I left",w:3,c:"past"},
{f:"je suis resté(e)",e:"I stayed",w:3,c:"past"},
{f:"je me suis levé(e)",e:"I got up (reflexive)",w:3,c:"past"},
{f:"hier soir",e:"last night",w:3,c:"time"},
{f:"la semaine dernière",e:"last week",w:3,c:"time"},
{f:"il y a deux jours",e:"two days ago",w:3,c:"time"},
{f:"déjà",e:"already",w:3,c:"time"},
{f:"pas encore",e:"not yet",w:3,c:"time"},
{f:"ensuite",e:"then / next",w:3,c:"time"},
{f:"après",e:"after",w:3,c:"time"},
{f:"avant",e:"before",w:3,c:"time"},
{f:"pendant",e:"during",w:3,c:"time"},
{f:"toujours",e:"always / still",w:3,c:"time"},
{f:"souvent",e:"often",w:3,c:"time"},
{f:"parfois",e:"sometimes",w:3,c:"time"},
{f:"jamais",e:"never",w:3,c:"time"},
{f:"se lever",e:"to get up",w:3,c:"routine"},
{f:"se réveiller",e:"to wake up",w:3,c:"routine"},
{f:"se doucher",e:"to shower",w:3,c:"routine"},
{f:"s'habiller",e:"to get dressed",w:3,c:"routine"},
{f:"se coucher",e:"to go to bed",w:3,c:"routine"},
{f:"dormir",e:"to sleep",w:3,c:"routine"},
{f:"je dors",e:"I sleep",w:3,c:"routine"},
{f:"cuisiner",e:"to cook",w:3,c:"routine"},
{f:"nettoyer",e:"to clean",w:3,c:"routine"},
{f:"se reposer",e:"to rest",w:3,c:"routine"},
{f:"sortir",e:"to go out",w:3,c:"routine"},
{f:"rentrer",e:"to go/come home",w:3,c:"routine"},
{f:"lire",e:"to read",w:3,c:"routine"},
{f:"je lis",e:"I read",w:3,c:"routine"},
{f:"écrire",e:"to write",w:3,c:"routine"},
{f:"j'écris",e:"I write",w:3,c:"routine"},
{f:"apprendre",e:"to learn",w:3,c:"routine"},
{f:"j'apprends le français",e:"I'm learning French",w:3,c:"routine"},
{f:"quel temps fait-il ?",e:"what's the weather like?",w:3,c:"weather"},
{f:"il fait beau",e:"the weather is nice",w:3,c:"weather"},
{f:"il fait chaud",e:"it's hot",w:3,c:"weather"},
{f:"il fait froid",e:"it's cold",w:3,c:"weather"},
{f:"il pleut",e:"it's raining",w:3,c:"weather"},
{f:"il neige",e:"it's snowing",w:3,c:"weather"},
{f:"le soleil",e:"the sun",w:3,c:"weather"},
{f:"la pluie",e:"the rain",w:3,c:"weather"},
{f:"le vent",e:"the wind",w:3,c:"weather"},
{f:"la tête",e:"the head",w:3,c:"body"},
{f:"la main",e:"the hand",w:3,c:"body"},
{f:"les yeux",e:"the eyes",w:3,c:"body"},
{f:"la bouche",e:"the mouth",w:3,c:"body"},
{f:"le pied",e:"the foot",w:3,c:"body"},
{f:"j'ai mal à la tête",e:"I have a headache",w:3,c:"health"},
{f:"je suis malade",e:"I am sick",w:3,c:"health"},
{f:"le médecin",e:"the doctor",w:3,c:"health"},
{f:"la pharmacie",e:"the pharmacy",w:3,c:"health"},
{f:"aider",e:"to help",w:3,c:"verbs"},
{f:"pouvez-vous m'aider ?",e:"can you help me?",w:3,c:"survival"},
{f:"attendre",e:"to wait",w:3,c:"verbs"},
{f:"commencer",e:"to begin",w:3,c:"verbs"},
{f:"finir",e:"to finish",w:3,c:"verbs"},
{f:"choisir",e:"to choose",w:3,c:"verbs"},
{f:"venir",e:"to come",w:3,c:"verbs"},
{f:"je viens",e:"I come",w:3,c:"verbs"},
{f:"savoir",e:"to know (facts)",w:3,c:"verbs"},
{f:"connaître",e:"to know (people/places)",w:3,c:"verbs"},
{f:"dire",e:"to say",w:3,c:"verbs"},
{f:"voir",e:"to see",w:3,c:"verbs"},
{f:"donc",e:"so / therefore",w:3,c:"connectors"},
{f:"alors",e:"so / then / well",w:3,c:"connectors"},
{f:"puis",e:"then",w:3,c:"connectors"},
{f:"quelque chose",e:"something",w:3,c:"basics"},
{f:"quelqu'un",e:"someone",w:3,c:"basics"},
{f:"tout / tous",e:"all / everything",w:3,c:"basics"},
{f:"rien",e:"nothing",w:3,c:"basics"},

// ---------- WEEK 4: opinions, future, feelings, travel, A2 connectors ----------
{f:"je pense que…",e:"I think that…",w:4,c:"opinions"},
{f:"à mon avis",e:"in my opinion",w:4,c:"opinions"},
{f:"je crois que…",e:"I believe that…",w:4,c:"opinions"},
{f:"je suis d'accord",e:"I agree",w:4,c:"opinions"},
{f:"je ne suis pas d'accord",e:"I disagree",w:4,c:"opinions"},
{f:"c'est vrai",e:"that's true",w:4,c:"opinions"},
{f:"c'est faux",e:"that's false",w:4,c:"opinions"},
{f:"j'espère que…",e:"I hope that…",w:4,c:"opinions"},
{f:"il me semble que…",e:"it seems to me that…",w:4,c:"opinions"},
{f:"le week-end prochain",e:"next weekend",w:4,c:"future"},
{f:"l'année prochaine",e:"next year",w:4,c:"future"},
{f:"je vais voyager",e:"I'm going to travel",w:4,c:"future"},
{f:"je vais essayer",e:"I'm going to try",w:4,c:"future"},
{f:"j'aimerais…",e:"I would like… (wish)",w:4,c:"future"},
{f:"je veux devenir…",e:"I want to become…",w:4,c:"future"},
{f:"heureux / heureuse",e:"happy (m. / f.)",w:4,c:"feelings"},
{f:"triste",e:"sad",w:4,c:"feelings"},
{f:"en colère",e:"angry",w:4,c:"feelings"},
{f:"surpris / surprise",e:"surprised",w:4,c:"feelings"},
{f:"inquiet / inquiète",e:"worried",w:4,c:"feelings"},
{f:"j'ai peur de…",e:"I'm afraid of…",w:4,c:"feelings"},
{f:"ça me plaît",e:"I like it (it pleases me)",w:4,c:"feelings"},
{f:"ça m'énerve",e:"it annoys me",w:4,c:"feelings"},
{f:"le voyage",e:"the trip",w:4,c:"travel"},
{f:"les vacances",e:"the holidays",w:4,c:"travel"},
{f:"le billet",e:"the ticket",w:4,c:"travel"},
{f:"le train",e:"the train",w:4,c:"travel"},
{f:"l'avion",e:"the plane",w:4,c:"travel"},
{f:"la voiture",e:"the car",w:4,c:"travel"},
{f:"le vélo",e:"the bicycle",w:4,c:"travel"},
{f:"le bus",e:"the bus",w:4,c:"travel"},
{f:"l'hôtel",e:"the hotel",w:4,c:"travel"},
{f:"la plage",e:"the beach",w:4,c:"travel"},
{f:"la montagne",e:"the mountain",w:4,c:"travel"},
{f:"le pays",e:"the country",w:4,c:"travel"},
{f:"l'étranger",e:"abroad / foreigner",w:4,c:"travel"},
{f:"réserver",e:"to book / reserve",w:4,c:"travel"},
{f:"visiter",e:"to visit (places)",w:4,c:"travel"},
{f:"le travail",e:"the work / job",w:4,c:"work"},
{f:"le bureau",e:"the office / desk",w:4,c:"work"},
{f:"l'ordinateur",e:"the computer",w:4,c:"work"},
{f:"le téléphone",e:"the phone",w:4,c:"work"},
{f:"envoyer un message",e:"to send a message",w:4,c:"work"},
{f:"le projet",e:"the project",w:4,c:"work"},
{f:"le jeu vidéo",e:"the video game",w:4,c:"hobbies"},
{f:"la musique",e:"the music",w:4,c:"hobbies"},
{f:"le film",e:"the movie",w:4,c:"hobbies"},
{f:"le livre",e:"the book",w:4,c:"hobbies"},
{f:"le sport",e:"the sport",w:4,c:"hobbies"},
{f:"faire du sport",e:"to do sports",w:4,c:"hobbies"},
{f:"la langue",e:"the language",w:4,c:"hobbies"},
{f:"la langue des signes",e:"sign language",w:4,c:"hobbies"},
{f:"cependant",e:"however",w:4,c:"connectors"},
{f:"par exemple",e:"for example",w:4,c:"connectors"},
{f:"c'est-à-dire",e:"that is to say",w:4,c:"connectors"},
{f:"en fait",e:"actually / in fact",w:4,c:"connectors"},
{f:"bien sûr",e:"of course",w:4,c:"connectors"},
{f:"peut-être que…",e:"maybe…",w:4,c:"connectors"},
{f:"si",e:"if / yes (contradicting)",w:4,c:"connectors"},
{f:"quand même",e:"anyway / still",w:4,c:"connectors"},
{f:"d'abord",e:"first of all",w:4,c:"connectors"},
{f:"enfin",e:"finally",w:4,c:"connectors"},
{f:"mieux",e:"better",w:4,c:"basics"},
{f:"pire",e:"worse",w:4,c:"basics"},
{f:"plus… que",e:"more… than",w:4,c:"basics"},
{f:"moins… que",e:"less… than",w:4,c:"basics"},
{f:"le meilleur",e:"the best",w:4,c:"basics"},
{f:"trop",e:"too much",w:4,c:"basics"},
{f:"assez",e:"enough / quite",w:4,c:"basics"},
{f:"presque",e:"almost",w:4,c:"basics"},
{f:"vraiment",e:"really",w:4,c:"basics"},
{f:"peu à peu",e:"little by little",w:4,c:"basics"}
],

phrases: [
{f:"Je m'appelle Psy et j'apprends le français.",e:"My name is Psy and I'm learning French.",w:1},
{f:"Je viens du Bangladesh.",e:"I come from Bangladesh.",w:1},
{f:"J'ai vingt ans.",e:"I am twenty years old. (avoir, not être!)",w:1},
{f:"Qu'est-ce que tu fais dans la vie ?",e:"What do you do for a living?",w:1},
{f:"Je suis désolé, je ne parle pas bien français.",e:"I'm sorry, I don't speak French well.",w:1},
{f:"Vous pouvez parler plus lentement, s'il vous plaît ?",e:"Can you speak more slowly, please?",w:1},
{f:"Je voudrais un café, s'il vous plaît.",e:"I'd like a coffee, please.",w:2},
{f:"Est-ce que vous avez une table pour deux ?",e:"Do you have a table for two?",w:2},
{f:"Où sont les toilettes ?",e:"Where are the toilets?",w:2},
{f:"Je cherche la gare.",e:"I'm looking for the train station.",w:2},
{f:"C'est combien, ça ?",e:"How much is that?",w:2},
{f:"Je vais prendre le poulet avec du riz.",e:"I'll have the chicken with rice.",w:2},
{f:"Ma famille habite loin d'ici.",e:"My family lives far from here.",w:2},
{f:"Ce week-end, je vais jouer aux jeux vidéo.",e:"This weekend, I'm going to play video games.",w:2},
{f:"Hier, j'ai étudié le français pendant deux heures.",e:"Yesterday, I studied French for two hours.",w:3},
{f:"Ce matin, je me suis levé à huit heures.",e:"This morning, I got up at eight.",w:3},
{f:"Je suis allé au marché et j'ai acheté des fruits.",e:"I went to the market and bought some fruit.",w:3},
{f:"Qu'est-ce que tu as fait hier soir ?",e:"What did you do last night?",w:3},
{f:"Je n'ai pas encore fini mon projet.",e:"I haven't finished my project yet.",w:3},
{f:"Il a plu toute la journée.",e:"It rained all day.",w:3},
{f:"J'apprends aussi la langue des signes américaine.",e:"I'm also learning American Sign Language.",w:3},
{f:"À mon avis, c'est une bonne idée.",e:"In my opinion, it's a good idea.",w:4},
{f:"Je pense que le français est plus facile qu'avant.",e:"I think French is easier than before.",w:4},
{f:"L'année prochaine, j'aimerais visiter la France.",e:"Next year, I'd like to visit France.",w:4},
{f:"D'abord je travaille, ensuite je joue, enfin je dors.",e:"First I work, then I play, finally I sleep.",w:4},
{f:"En fait, j'ai commencé il y a seulement un mois.",e:"Actually, I started only a month ago.",w:4},
{f:"Je parle français mieux qu'avant, peu à peu.",e:"I speak French better than before, little by little.",w:4},
{f:"Si tu veux, on peut parler en français.",e:"If you want, we can talk in French.",w:4}
],

quizzes: [
{w:1,q:"« J'ai 25 ans » — why 'avoir' and not 'être'?",o:["French uses 'to have' for age","It's a spelling mistake","Both are correct","'être' is only for objects"],a:0},
{w:1,q:"Which is the correct question: 'Where do you live?'",o:["Où tu habites quoi ?","Où est-ce que tu habites ?","Quand tu habites ?","Comment habites ?"],a:1},
{w:1,q:"'We are' in French:",o:["nous avons","nous allons","nous sommes","vous êtes"],a:2},
{w:1,q:"Pick the right article: ___ femme",o:["le","la","un","les"],a:1},
{w:1,q:"'soixante-dix' = ?",o:["60","70","80","90"],a:1},
{w:1,q:"'I don't understand':",o:["Je ne comprends pas","Je comprends non","Ne je comprends","Je pas comprends"],a:0},
{w:1,q:"'ils ont' means:",o:["they are","they go","they have","they do"],a:2},
{w:1,q:"The final letters in 'vous' and 'parlez' are:",o:["Always pronounced","Silent (usually)","Pronounced only on Sundays","Pronounced as 'z' and 'x'"],a:1},
{w:1,q:"'quatre-vingt-dix' = ?",o:["70","80","90","100"],a:2},
{w:1,q:"Formal 'you' in French is:",o:["tu","vous","il","on"],a:1},
{w:1,q:"'Qu'est-ce que c'est ?' means:",o:["Who is it?","Where is it?","What is it?","How is it?"],a:2},
{w:1,q:"'Elle va' means:",o:["She has","She is","She goes","She does"],a:2},
{w:2,q:"Negation: 'Je ___ mange ___ de viande.'",o:["ne / pas","pas / ne","non / pas","ne / non"],a:0},
{w:2,q:"'I would like a coffee' (polite):",o:["Je veux un café","Je voudrais un café","J'ai un café","Je vais café"],a:1},
{w:2,q:"Near future: 'I am going to eat':",o:["Je mange aller","Je vais manger","Je manger vais","J'ai mangé"],a:1},
{w:2,q:"'tu parles', 'il parle', 'nous ___':",o:["parlons","parlez","parles","parlent"],a:0},
{w:2,q:"Feminine of 'bon':",o:["bone","bonne","bonna","bons"],a:1},
{w:2,q:"'Il y a un marché près d'ici' means:",o:["There will be a market","There is a market nearby","I have a market","He has a market here"],a:1},
{w:2,q:"'the bill, please' at a restaurant:",o:["Le billet, s'il vous plaît","L'addition, s'il vous plaît","L'argent, s'il vous plaît","Le menu, s'il vous plaît"],a:1},
{w:2,q:"'à droite' means:",o:["straight ahead","to the left","to the right","behind"],a:2},
{w:2,q:"Which day is 'mercredi'?",o:["Tuesday","Wednesday","Thursday","Friday"],a:1},
{w:2,q:"'J'ai faim' literally means:",o:["I am hungry","I have hunger","I eat now","I want food"],a:1},
{w:2,q:"Most French nouns ending in -tion are:",o:["masculine","feminine","plural only","verbs"],a:1},
{w:2,q:"'C'est trop cher' means:",o:["It's very good","It's too expensive","It's too far","It's my dear"],a:1},
{w:3,q:"Passé composé of 'manger' (je):",o:["je mangeais","j'ai mangé","je suis mangé","je mangerai"],a:1},
{w:3,q:"Which verb uses 'être' in passé composé?",o:["manger","parler","aller","faire"],a:2},
{w:3,q:"'Je suis allée' — the extra 'e' means the speaker is:",o:["male","female","plural","formal"],a:1},
{w:3,q:"'I got up at 8': 'Je ___ levé(e) à huit heures.'",o:["ai","suis","me suis","m'ai"],a:2},
{w:3,q:"'pas encore' means:",o:["not yet","never","not much","no more"],a:0},
{w:3,q:"Past participle of 'voir':",o:["vu","voyé","vis","voir"],a:0},
{w:3,q:"'What did you do yesterday?':",o:["Qu'est-ce que tu fais hier ?","Qu'est-ce que tu as fait hier ?","Quoi tu as fait hier ?","Qu'as-tu faire hier ?"],a:1},
{w:3,q:"'Il pleut' means:",o:["It's sunny","It's raining","It's cold","It's late"],a:1},
{w:3,q:"'savoir' vs 'connaître': you ___ a fact, you ___ a person.",o:["savez / connaissez","connaissez / savez","avez / êtes","voyez / savez"],a:0},
{w:3,q:"'la semaine dernière' means:",o:["next week","this week","last week","every week"],a:2},
{w:3,q:"'Je n'ai rien fait' means:",o:["I did nothing","I did everything","I never do it","Nothing did me"],a:0},
{w:3,q:"'souvent' means:",o:["sometimes","often","never","always"],a:1},
{w:4,q:"'À mon avis' means:",o:["at my house","in my opinion","by the way","on my life"],a:1},
{w:4,q:"'more interesting than':",o:["plus intéressant que","moins intéressant que","aussi intéressant","trop intéressant que"],a:0},
{w:4,q:"'J'aimerais visiter Paris' expresses:",o:["a past action","a polite wish","an order","a fear"],a:1},
{w:4,q:"Order the story: 'd'abord… ensuite… ___'",o:["enfin","avant","déjà","hier"],a:0},
{w:4,q:"'cependant' means:",o:["because","however","therefore","meanwhile"],a:1},
{w:4,q:"'I disagree':",o:["Je suis d'accord","Je ne suis pas d'accord","Je n'accord pas","Je suis désaccord"],a:1},
{w:4,q:"'en fait' means:",o:["in fact / actually","finally","in doing","by making"],a:0},
{w:4,q:"'le meilleur' means:",o:["the worst","the biggest","the best","the oldest"],a:2},
{w:4,q:"'Si tu veux' means:",o:["If you want","Yes you want","So you want","When you want"],a:0},
{w:4,q:"Which sentence is correct A2 French?",o:["Hier je vais au marché","Hier je suis allé au marché","Hier je aller au marché","Hier j'allé au marché"],a:1},
{w:4,q:"'quand même' means:",o:["when even","anyway / still","sometimes","right now"],a:1},
{w:4,q:"'peu à peu' means:",o:["very little","little by little","a few people","almost never"],a:1}
]
},

asl: {
alphabet: [
{l:"A",d:"Fist, thumb alongside the fingers (not tucked in)"},
{l:"B",d:"Flat hand, fingers together pointing up, thumb folded across palm"},
{l:"C",d:"Hand curved like holding a cup — a 'C' shape"},
{l:"D",d:"Index finger up, other fingertips touch the thumb making a circle"},
{l:"E",d:"Fingertips folded down touching the thumb — small squished claw"},
{l:"F",d:"Index and thumb make a circle, other three fingers up and spread"},
{l:"G",d:"Index and thumb flat, parallel, pointing sideways"},
{l:"H",d:"Index and middle fingers together pointing sideways, palm in"},
{l:"I",d:"Fist with pinky finger up"},
{l:"J",d:"Pinky up, draw a 'J' in the air"},
{l:"K",d:"Index and middle up in a V, thumb touching between them"},
{l:"L",d:"Index up, thumb out — an 'L' shape"},
{l:"M",d:"Thumb tucked under first three fingers"},
{l:"N",d:"Thumb tucked under first two fingers"},
{l:"O",d:"All fingertips meet the thumb — round 'O' shape"},
{l:"P",d:"Like K but pointing downward"},
{l:"Q",d:"Like G but pointing downward"},
{l:"R",d:"Index and middle fingers crossed"},
{l:"S",d:"Fist with thumb across the front of the fingers"},
{l:"T",d:"Thumb tucked between index and middle fingers"},
{l:"U",d:"Index and middle together pointing up"},
{l:"V",d:"Index and middle up, spread apart — 'V' / peace sign"},
{l:"W",d:"Index, middle, ring up and spread"},
{l:"X",d:"Index finger bent like a hook"},
{l:"Y",d:"Thumb and pinky out — 'hang loose'"},
{l:"Z",d:"Index finger draws a 'Z' in the air"}
],
signs: [
{s:"HELLO",d:"Flat hand at forehead, move out — like a small salute",w:1},
{s:"THANK-YOU",d:"Flat hand at chin, move forward toward the person",w:1},
{s:"PLEASE",d:"Flat hand on chest, circular rub",w:1},
{s:"SORRY",d:"'A' fist on chest, circular rub, sorry face",w:1},
{s:"YES",d:"'S' fist nods up and down like a head",w:1},
{s:"NO",d:"Index+middle fingers tap thumb (like a mouth snapping shut)",w:1},
{s:"NAME",d:"'H' hands, tap one on the other twice (X shape)",w:1},
{s:"MY / MINE",d:"Flat palm on chest",w:1},
{s:"YOUR",d:"Flat palm pushes toward the person",w:1},
{s:"ME / I",d:"Index finger points at your chest",w:1},
{s:"YOU",d:"Index finger points at the person",w:1},
{s:"WHAT",d:"Both palms up, small shake, eyebrows DOWN",w:1},
{s:"WHERE",d:"Index finger up, shake side to side, eyebrows DOWN",w:1},
{s:"WHO",d:"Thumb on chin, index finger bends twice, eyebrows DOWN",w:1},
{s:"DEAF",d:"Index finger touches ear then mouth",w:1},
{s:"HEARING (person)",d:"Index finger rolls forward in front of mouth",w:1},
{s:"LEARN",d:"Hand picks up 'knowledge' from palm and puts it on forehead",w:1},
{s:"SIGN (ASL)",d:"Both index fingers circle alternately toward you",w:1},
{s:"UNDERSTAND",d:"Index finger flicks up near forehead",w:1},
{s:"NOT-UNDERSTAND",d:"Same + head shake",w:1},
{s:"SLOW",d:"One hand strokes slowly up the back of the other",w:1},
{s:"AGAIN",d:"Bent hand taps fingertips into opposite palm",w:1},
{s:"GOOD",d:"Flat hand from chin down into other palm",w:1},
{s:"BAD",d:"Flat hand from chin, flips down and away",w:1},
{s:"NICE-MEET-YOU",d:"Two index fingers (people) come together",w:1},
{s:"MOTHER",d:"Open '5' hand, thumb taps chin",w:2},
{s:"FATHER",d:"Open '5' hand, thumb taps forehead",w:2},
{s:"SISTER",d:"'A'-to-'L' at chin (girl) then index fingers together",w:2},
{s:"BROTHER",d:"'A'-to-'L' at forehead (boy) then index fingers together",w:2},
{s:"FAMILY",d:"Two 'F' hands make a circle forward",w:2},
{s:"FRIEND",d:"Index fingers hook together, then swap",w:2},
{s:"BOY",d:"Fingers snap closed at forehead (cap brim)",w:2},
{s:"GIRL",d:"Thumb strokes down the jawline",w:2},
{s:"HAPPY",d:"Flat hand(s) brush up the chest twice, happy face",w:2},
{s:"SAD",d:"Both open hands slide down in front of face, sad face",w:2},
{s:"ANGRY",d:"Claw hand pulls up in front of face, angry face",w:2},
{s:"TIRED",d:"Bent hands on chest collapse downward",w:2},
{s:"HUNGRY",d:"'C' hand slides down the chest once",w:2},
{s:"LIKE",d:"Thumb+middle finger pull out from chest",w:2},
{s:"DON'T-LIKE",d:"Same but flick fingers away + head shake",w:2},
{s:"WANT",d:"Both claw hands pull toward you",w:2},
{s:"HAVE",d:"Bent-hand fingertips touch chest",w:2},
{s:"NEED",d:"'X' finger bends down twice",w:2},
{s:"HELP",d:"Fist on flat palm, both lift together",w:2},
{s:"EAT",d:"Flat 'O' taps mouth",w:2},
{s:"DRINK",d:"'C' hand tips at mouth like a cup",w:2},
{s:"WATER",d:"'W' taps chin",w:2},
{s:"MILK",d:"Squeeze fist (milking)",w:2},
{s:"HOME",d:"Flat 'O' touches cheek in two spots (eat + sleep)",w:2},
{s:"SCHOOL",d:"Clap flat hands twice",w:2},
{s:"WORK",d:"'S' fist taps wrist of other fist twice",w:2},
{s:"PLAY",d:"'Y' hands shake",w:2},
{s:"MORE",d:"Flat 'O' fingertips tap together",w:2},
{s:"FINISH",d:"Open '5' hands flip outward",w:2},
{s:"GO",d:"Both index fingers arc forward",w:2},
{s:"COME",d:"Both index fingers arc toward you",w:2},
{s:"TODAY",d:"'Y' hands (NOW) drop twice",w:3},
{s:"TOMORROW",d:"Thumb ('A') at cheek arcs forward",w:3},
{s:"YESTERDAY",d:"Thumb ('A') at cheek arcs backward",w:3},
{s:"NOW",d:"Both 'Y' hands drop once",w:3},
{s:"LATER",d:"'L' pivots forward on other palm",w:3},
{s:"MORNING",d:"Arm rises like the sun over the horizon-arm",w:3},
{s:"NIGHT",d:"Bent hand sets over the horizon-arm",w:3},
{s:"WEEK",d:"Index-hand slides across the palm",w:3},
{s:"MONTH",d:"Index finger slides down the other index",w:3},
{s:"YEAR",d:"'S' fist orbits the other fist once",w:3},
{s:"MONDAY",d:"'M' hand small circle (weekdays = initial + circle)",w:3},
{s:"FRIDAY",d:"'F' hand small circle",w:3},
{s:"BIRTHDAY",d:"BIRTH + DAY (varies by region)",w:3},
{s:"EVERY-DAY",d:"'A' thumb on cheek slides forward repeatedly",w:3},
{s:"SLEEP",d:"Open hand closes down over the face",w:3},
{s:"WAKE-UP",d:"Closed hands at eyes pop open",w:3},
{s:"SHOWER",d:"Claw hand above head 'sprays' twice",w:3},
{s:"COOK",d:"Flat hand flips on other palm (pancake)",w:3},
{s:"BUY",d:"Flat 'O' (money) moves off the palm forward",w:3},
{s:"STORE",d:"Both flat-'O' hands swing forward twice",w:3},
{s:"TIME",d:"Bent index taps the wrist (watch)",w:3},
{s:"HOW-MANY",d:"Fists flick open upward, eyebrows down",w:3},
{s:"OLD (age)",d:"'C' at chin pulls down into 'S' (beard)",w:3},
{s:"LIVE / ADDRESS",d:"Both 'A'/'L' hands slide up the torso",w:3},
{s:"READ",d:"'V' fingers scan down the other palm",w:4},
{s:"WRITE",d:"Pinched fingers 'write' across the palm",w:4},
{s:"BOOK",d:"Flat palms open like a book",w:4},
{s:"MOVIE",d:"Open '5' hand shimmers past the other palm",w:4},
{s:"GAME",d:"Two 'A' thumbs-up knock together",w:4},
{s:"COMPUTER",d:"'C' hand arcs up the opposite arm",w:4},
{s:"INTERNET",d:"Middle fingers touch, pivot both hands",w:4},
{s:"PRACTICE",d:"'A' fist rubs back and forth along the other index",w:4},
{s:"REMEMBER",d:"Thumb from forehead lands on other thumb",w:4},
{s:"FORGET",d:"Flat hand wipes across forehead into 'A'",w:4},
{s:"KNOW",d:"Bent-hand fingertips tap temple",w:4},
{s:"DON'T-KNOW",d:"KNOW then hand flips away + head shake",w:4},
{s:"THINK",d:"Index finger circles at temple then touches it",w:4},
{s:"FEEL",d:"Middle finger strokes up the chest",w:4},
{s:"BEAUTIFUL",d:"'5' hand circles the face closing to flat-'O', opens",w:4},
{s:"IMPORTANT",d:"'F' hands rise and twist together",w:4},
{s:"CAN (able)",d:"Both 'S'/'A' fists drop firmly together",w:4},
{s:"CAN'T",d:"Index finger strikes down past the other index",w:4},
{s:"MUST / NEED-TO",d:"'X' hook presses down once",w:4},
{s:"TRY",d:"Both 'A'/'S' fists push forward with effort",w:4},
{s:"WITH",d:"Both 'A' fists come together, knuckles touching",w:4},
{s:"WITHOUT",d:"WITH, then hands open and separate",w:4},
{s:"SAME",d:"'Y' hand moves between you and the person",w:4},
{s:"DIFFERENT",d:"Crossed index fingers pull apart",w:4}
],
grammarTips: [
"ASL is NOT signed English — it has its own grammar. Word order is usually TOPIC then COMMENT: 'STORE I GO' (I'm going to the store).",
"There is no sign for 'is/am/are'. 'She is happy' = point at her + HAPPY.",
"Yes/no questions: eyebrows UP. Wh-questions (what/where/who): eyebrows DOWN. Facial grammar is mandatory, not decoration.",
"Time goes first: 'YESTERDAY STORE I GO' = I went to the store yesterday. Establishing the time frame replaces verb tense.",
"Fingerspell names, brands, and words you don't know a sign for. Keep your hand steady near your shoulder — don't bounce letters.",
"Mouth morphemes matter: some signs need specific mouth shapes (like 'cha' for BIG). Copy Dr. Vicars' face, not just his hands.",
"Pointing (indexing) is grammar: set a person up in space once, then point to that spot to mean 'he/she' for the rest of the conversation."
]
},

// ============ Visual French: picture -> word -> pronunciation ============
visual: [
// food & drink
{i:"🍞",f:"le pain",e:"the bread",g:"food",p:"img/bread.jpg"},
{i:"💧",f:"l'eau",e:"the water",g:"food",p:"img/water.jpg"},
{i:"☕",f:"le café",e:"the coffee",g:"food",p:"img/coffee.jpg"},
{i:"🍵",f:"le thé",e:"the tea",g:"food",p:"img/tea.jpg"},
{i:"🥛",f:"le lait",e:"the milk",g:"food",p:"img/milk.jpg"},
{i:"🧀",f:"le fromage",e:"the cheese",g:"food",p:"img/cheese.jpg"},
{i:"🥩",f:"la viande",e:"the meat",g:"food",p:"img/meat.jpg"},
{i:"🍗",f:"le poulet",e:"the chicken",g:"food",p:"img/chicken.jpg"},
{i:"🐟",f:"le poisson",e:"the fish",g:"food",p:"img/fish.jpg"},
{i:"🥕",f:"les légumes",e:"the vegetables",g:"food",p:"img/vegetables.jpg"},
{i:"🍎",f:"la pomme",e:"the apple",g:"food",p:"img/apple.jpg"},
{i:"🍌",f:"la banane",e:"the banana",g:"food",p:"img/banana.jpg"},
{i:"🍊",f:"l'orange",e:"the orange",g:"food",p:"img/orange.jpg"},
{i:"🍚",f:"le riz",e:"the rice",g:"food",p:"img/rice.jpg"},
{i:"🥚",f:"l'œuf",e:"the egg",g:"food",p:"img/egg.jpg"},
{i:"🍕",f:"la pizza",e:"the pizza",g:"food",p:"img/pizza.jpg"},
{i:"🍫",f:"le chocolat",e:"the chocolate",g:"food",p:"img/chocolate.jpg"},
{i:"🍰",f:"le gâteau",e:"the cake",g:"food",p:"img/cake.jpg"},
{i:"🥗",f:"la salade",e:"the salad",g:"food",p:"img/salad.jpg"},
{i:"🍜",f:"la soupe",e:"the soup",g:"food",p:"img/soup.jpg"},
{i:"🧈",f:"le beurre",e:"the butter",g:"food",p:"img/butter.jpg"},
{i:"🍬",f:"le sucre",e:"the sugar",g:"food",p:"img/sugar.jpg"},
{i:"🧂",f:"le sel",e:"the salt",g:"food",p:"img/salt.jpg"},
{i:"🍷",f:"le vin",e:"the wine",g:"food",p:"img/wine.jpg"},
{i:"🥤",f:"le jus",e:"the juice",g:"food",p:"img/juice.jpg"},
// animals
{i:"🐱",f:"le chat",e:"the cat",g:"animals",p:"img/cat.jpg"},
{i:"🐶",f:"le chien",e:"the dog",g:"animals",p:"img/dog.jpg"},
{i:"🐦",f:"l'oiseau",e:"the bird",g:"animals",p:"img/bird.jpg"},
{i:"🐴",f:"le cheval",e:"the horse",g:"animals",p:"img/horse.jpg"},
{i:"🐮",f:"la vache",e:"the cow",g:"animals",p:"img/cow.jpg"},
{i:"🐭",f:"la souris",e:"the mouse",g:"animals",p:"img/mouse.jpg"},
{i:"🐰",f:"le lapin",e:"the rabbit",g:"animals",p:"img/rabbit.jpg"},
{i:"🦁",f:"le lion",e:"the lion",g:"animals",p:"img/lion.jpg"},
{i:"🐘",f:"l'éléphant",e:"the elephant",g:"animals",p:"img/elephant.jpg"},
{i:"🐍",f:"le serpent",e:"the snake",g:"animals",p:"img/snake.jpg"},
// objects
{i:"📱",f:"le téléphone",e:"the phone",g:"objects",p:"img/phone.jpg"},
{i:"💻",f:"l'ordinateur",e:"the computer",g:"objects",p:"img/computer.jpg"},
{i:"📖",f:"le livre",e:"the book",g:"objects",p:"img/book.jpg"},
{i:"🔑",f:"la clé",e:"the key",g:"objects",p:"img/key.jpg"},
{i:"🚪",f:"la porte",e:"the door",g:"objects",p:"img/door.jpg"},
{i:"🪟",f:"la fenêtre",e:"the window",g:"objects",p:"img/window.jpg"},
{i:"🛏️",f:"le lit",e:"the bed",g:"objects",p:"img/bed.jpg"},
{i:"🪑",f:"la chaise",e:"the chair",g:"objects",p:"img/chair.jpg"},
{i:"🍽️",f:"l'assiette",e:"the plate",g:"objects",p:"img/plate.jpg"},
{i:"🥄",f:"la cuillère",e:"the spoon",g:"objects",p:"img/spoon.jpg"},
{i:"🔪",f:"le couteau",e:"the knife",g:"objects",p:"img/knife.jpg"},
{i:"🍴",f:"la fourchette",e:"the fork",g:"objects",p:"img/fork.jpg"},
{i:"👕",f:"la chemise",e:"the shirt",g:"objects",p:"img/shirt.jpg"},
{i:"👖",f:"le pantalon",e:"the trousers",g:"objects",p:"img/trousers.jpg"},
{i:"👟",f:"les chaussures",e:"the shoes",g:"objects",p:"img/shoes.jpg"},
{i:"🎒",f:"le sac",e:"the bag",g:"objects",p:"img/bag.jpg"},
{i:"⌚",f:"la montre",e:"the watch",g:"objects",p:"img/watch.jpg"},
{i:"🕶️",f:"les lunettes",e:"the glasses",g:"objects",p:"img/glasses.jpg"},
{i:"💶",f:"l'argent",e:"the money",g:"objects",p:"img/money.jpg"},
{i:"✏️",f:"le crayon",e:"the pencil",g:"objects",p:"img/pencil.jpg"},
{i:"📄",f:"le papier",e:"the paper",g:"objects",p:"img/paper.jpg"},
{i:"🎮",f:"le jeu vidéo",e:"the video game",g:"objects",p:"img/videogame.jpg"},
{i:"🎵",f:"la musique",e:"the music",g:"objects"},
{i:"📺",f:"la télévision",e:"the television",g:"objects",p:"img/tv.jpg"},
{i:"📷",f:"l'appareil photo",e:"the camera",g:"objects",p:"img/camera.jpg"},
// places & transport
{i:"🏠",f:"la maison",e:"the house",g:"places",p:"img/house.jpg"},
{i:"🏢",f:"l'immeuble",e:"the building",g:"places",p:"img/building.jpg"},
{i:"🏫",f:"l'école",e:"the school",g:"places",p:"img/school.jpg"},
{i:"🏥",f:"l'hôpital",e:"the hospital",g:"places",p:"img/hospital.jpg"},
{i:"🏦",f:"la banque",e:"the bank",g:"places",p:"img/bank.jpg"},
{i:"🏪",f:"le magasin",e:"the shop",g:"places",p:"img/shop.jpg"},
{i:"🍽",f:"le restaurant",e:"the restaurant",g:"places",p:"img/restaurant.jpg"},
{i:"⛪",f:"l'église",e:"the church",g:"places",p:"img/church.jpg"},
{i:"🌉",f:"le pont",e:"the bridge",g:"places",p:"img/bridge.jpg"},
{i:"🏖️",f:"la plage",e:"the beach",g:"places",p:"img/beach.jpg"},
{i:"⛰️",f:"la montagne",e:"the mountain",g:"places",p:"img/mountain.jpg"},
{i:"🌊",f:"la mer",e:"the sea",g:"places",p:"img/sea.jpg"},
{i:"🌳",f:"l'arbre",e:"the tree",g:"places",p:"img/tree.jpg"},
{i:"🌸",f:"la fleur",e:"the flower",g:"places",p:"img/flower.jpg"},
{i:"🚗",f:"la voiture",e:"the car",g:"transport",p:"img/car.jpg"},
{i:"🚌",f:"le bus",e:"the bus",g:"transport",p:"img/bus.jpg"},
{i:"🚆",f:"le train",e:"the train",g:"transport",p:"img/train.jpg"},
{i:"✈️",f:"l'avion",e:"the plane",g:"transport",p:"img/plane.jpg"},
{i:"🚲",f:"le vélo",e:"the bicycle",g:"transport",p:"img/bicycle.jpg"},
{i:"🚕",f:"le taxi",e:"the taxi",g:"transport",p:"img/taxi.jpg"},
{i:"🚢",f:"le bateau",e:"the boat",g:"transport",p:"img/boat.jpg"},
// body
{i:"👤",f:"la tête",e:"the head",g:"body",p:"img/head.jpg"},
{i:"✋",f:"la main",e:"the hand",g:"body",p:"img/hand.jpg"},
{i:"👀",f:"les yeux",e:"the eyes",g:"body",p:"img/eyes.jpg"},
{i:"👄",f:"la bouche",e:"the mouth",g:"body",p:"img/mouth.jpg"},
{i:"👃",f:"le nez",e:"the nose",g:"body",p:"img/nose.jpg"},
{i:"👂",f:"l'oreille",e:"the ear",g:"body",p:"img/ear.jpg"},
{i:"🦶",f:"le pied",e:"the foot",g:"body",p:"img/foot.jpg"},
{i:"🦵",f:"la jambe",e:"the leg",g:"body",p:"img/leg.jpg"},
{i:"💪",f:"le bras",e:"the arm",g:"body",p:"img/arm.jpg"},
{i:"❤️",f:"le cœur",e:"the heart",g:"body",p:"img/heart.jpg"},
// nature & weather
{i:"☀️",f:"le soleil",e:"the sun",g:"weather",p:"img/sun.jpg"},
{i:"🌙",f:"la lune",e:"the moon",g:"weather",p:"img/moon.jpg"},
{i:"⭐",f:"l'étoile",e:"the star",g:"weather",p:"img/star.jpg"},
{i:"🌧️",f:"la pluie",e:"the rain",g:"weather",p:"img/rain.jpg"},
{i:"❄️",f:"la neige",e:"the snow",g:"weather",p:"img/snowpic.jpg"},
{i:"💨",f:"le vent",e:"the wind",g:"weather",p:"img/wind.jpg"},
{i:"☁️",f:"le nuage",e:"the cloud",g:"weather",p:"img/cloud.jpg"},
{i:"🔥",f:"le feu",e:"the fire",g:"weather",p:"img/fire.jpg"},
// colors
{i:"🔴",f:"rouge",e:"red",g:"colors"},
{i:"🔵",f:"bleu",e:"blue",g:"colors"},
{i:"🟢",f:"vert",e:"green",g:"colors"},
{i:"🟡",f:"jaune",e:"yellow",g:"colors"},
{i:"⚫",f:"noir",e:"black",g:"colors"},
{i:"⚪",f:"blanc",e:"white",g:"colors"},
{i:"🟠",f:"orange",e:"orange",g:"colors"},
{i:"🟣",f:"violet",e:"purple",g:"colors"},
{i:"🟤",f:"marron",e:"brown",g:"colors"},
{i:"🩷",f:"rose",e:"pink",g:"colors"},
// people
{i:"👨",f:"l'homme",e:"the man",g:"people"},
{i:"👩",f:"la femme",e:"the woman",g:"people"},
{i:"👦",f:"le garçon",e:"the boy",g:"people"},
{i:"👧",f:"la fille",e:"the girl",g:"people"},
{i:"👶",f:"le bébé",e:"the baby",g:"people",p:"img/baby.jpg"},
{i:"👪",f:"la famille",e:"the family",g:"people",p:"img/family.jpg"},
{i:"👴",f:"le grand-père",e:"the grandfather",g:"people"},
{i:"👵",f:"la grand-mère",e:"the grandmother",g:"people"},
{i:"🧑‍⚕️",f:"le médecin",e:"the doctor",g:"people",p:"img/doctor.jpg"},
{i:"👮",f:"le policier",e:"the police officer",g:"people",p:"img/police.jpg"}
],

// ============ Built-in French mini-lessons ============
lessons: [
{w:1,t:"How French sounds work",p:[
 {x:"Final consonants are usually SILENT: 'vous' sounds like 'voo', 'petit' like 'puh-TEE'. Exception: final C, R, F, L are often pronounced (think 'CaReFuL')."},
 {x:"Nasal vowels — air through the nose, don't pronounce the N: ", ex:[["bon","good — 'boh(n)'"],["vin","wine — 'vah(n)'"],["un","one — 'uh(n)'"]]},
 {x:"'ou' = 'oo', 'oi' = 'wa', 'au/eau' = 'oh', 'é' = 'ay', 'è/ê' = 'eh':", ex:[["bonjour","bohn-ZHOOR"],["moi","mwa — me"],["l'eau","loh — water"],["café","ka-FAY"]]},
 {x:"Liaison: a silent final consonant is pronounced when the next word starts with a vowel:", ex:[["vous êtes","voo-ZET — you are"],["les amis","lay-ZA-mee — the friends"]]}
]},
{w:1,t:"Gender & articles — every noun is m. or f.",p:[
 {x:"There's no logic to memorize word-by-word — ALWAYS learn a noun with its article:", ex:[["le pain","the bread (m.)"],["la pomme","the apple (f.)"],["un livre","a book (m.)"],["une table","a table (f.)"]]},
 {x:"Patterns that usually work: -tion/-té/-ette → feminine; -age/-ment/-eau → masculine:", ex:[["la nation","the nation"],["la liberté","freedom"],["le fromage","the cheese"],["le bâtiment","the building"]]},
 {x:"Before a vowel, le/la become l'; plural is always 'les':", ex:[["l'eau","the water"],["l'ami","the friend"],["les enfants","the children"]]}
]},
{w:1,t:"The big four verbs (present)",p:[
 {x:"ÊTRE (to be) and AVOIR (to have) are irregular and everywhere. Age uses AVOIR:", ex:[["je suis fatigué","I am tired"],["j'ai vingt ans","I am 20 (I HAVE 20 years)"],["tu es prêt ?","are you ready?"],["nous avons faim","we're hungry"]]},
 {x:"ALLER (to go) also builds the future. FAIRE (to do/make) covers weather and activities:", ex:[["je vais au marché","I go to the market"],["il fait beau","the weather's nice"],["nous faisons du sport","we do sports"]]}
]},
{w:1,t:"Asking questions",p:[
 {x:"Easiest way: put 'est-ce que' before a statement — no word-order change:", ex:[["Est-ce que tu parles français ?","Do you speak French?"],["Est-ce qu'il vient ?","Is he coming?"]]},
 {x:"Question words go in front: où (where), quand (when), pourquoi (why), comment (how), combien (how much):", ex:[["Où est la gare ?","Where's the station?"],["Comment tu t'appelles ?","What's your name?"],["C'est combien ?","How much is it?"]]},
 {x:"In speech you can just raise your voice at the end:", ex:[["Tu viens ?","You coming?"],["Ça va ?","All good?"]]}
]},
{w:2,t:"Regular -er verbs (90% of all verbs)",p:[
 {x:"Drop -er, add endings: je -e, tu -es, il -e, nous -ons, vous -ez, ils -ent. The -e/-es/-ent endings are SILENT, so 4 of 6 forms sound identical:", ex:[["je parle","I speak"],["tu parles","you speak (same sound!)"],["nous parlons","we speak"],["vous parlez","you speak"]]},
 {x:"This pattern covers hundreds of verbs:", ex:[["j'aime","I like"],["tu travailles","you work"],["elle écoute","she listens"],["ils jouent","they play"]]}
]},
{w:2,t:"Negation — the 'ne…pas' sandwich",p:[
 {x:"Wrap the verb between 'ne' and 'pas'. In speech, 'ne' often disappears:", ex:[["je ne sais pas","I don't know"],["je sais pas","I dunno (spoken)"],["il ne travaille pas","he doesn't work"]]},
 {x:"Variants: ne…jamais (never), ne…rien (nothing), ne…plus (no more):", ex:[["je ne mange jamais de viande","I never eat meat"],["je n'ai rien fait","I did nothing"]]}
]},
{w:2,t:"Near future: aller + infinitive",p:[
 {x:"Exactly like English 'going to'. Conjugate ALLER, then any verb in its dictionary form:", ex:[["je vais manger","I'm going to eat"],["tu vas aimer ça","you're going to like it"],["on va voir","we'll see"],["ils vont partir demain","they're going to leave tomorrow"]]},
 {x:"'on' = casual 'we' — French people use it constantly instead of 'nous':", ex:[["on y va ?","shall we go?"],["on parle français","we speak French"]]}
]},
{w:2,t:"Want, can, must — the power trio",p:[
 {x:"vouloir (want), pouvoir (can), devoir (must) + infinitive unlocks hundreds of sentences:", ex:[["je veux apprendre","I want to learn"],["je peux venir","I can come"],["je dois partir","I have to leave"],["tu peux m'aider ?","can you help me?"]]},
 {x:"'Je voudrais' (I would like) is the polite magic word for shops and cafés:", ex:[["je voudrais un café, s'il vous plaît","I'd like a coffee, please"]]}
]},
{w:3,t:"Passé composé — talking about the past",p:[
 {x:"avoir (conjugated) + past participle. For -er verbs the participle ends in -é:", ex:[["j'ai mangé","I ate"],["tu as parlé","you spoke"],["il a travaillé","he worked"],["nous avons joué","we played"]]},
 {x:"Common irregular participles — just memorize these:", ex:[["j'ai fait","I did"],["j'ai vu","I saw"],["j'ai pris","I took"],["j'ai eu","I had"],["j'ai été","I was"],["j'ai bu","I drank"]]}
]},
{w:3,t:"Être verbs & reflexives in the past",p:[
 {x:"Movement/change verbs use ÊTRE instead: aller, venir, arriver, partir, rester, rentrer… The participle agrees with the subject (add -e if you're female):", ex:[["je suis allé au parc","I went to the park (m.)"],["elle est allée au parc","she went to the park"],["nous sommes arrivés","we arrived"]]},
 {x:"Reflexive verbs (daily routine!) also use être:", ex:[["je me suis levé à 8h","I got up at 8"],["elle s'est couchée tard","she went to bed late"]]}
]},
{w:3,t:"Time words that glue stories together",p:[
 {x:"Sequence your day like a story:", ex:[["d'abord","first"],["ensuite","then"],["après","after"],["enfin","finally"],["hier soir","last night"],["il y a deux jours","two days ago"]]},
 {x:"Frequency: toujours (always), souvent (often), parfois (sometimes), jamais (never):", ex:[["je joue souvent le soir","I often play in the evening"],["je ne me lève jamais tôt","I never get up early"]]}
]},
{w:4,t:"Giving opinions like an A2 speaker",p:[
 {x:"These starters instantly upgrade your speech:", ex:[["je pense que c'est intéressant","I think it's interesting"],["à mon avis, c'est trop cher","in my opinion it's too expensive"],["je crois qu'il a raison","I believe he's right"],["il me semble que…","it seems to me that…"]]},
 {x:"Agreeing and disagreeing:", ex:[["je suis d'accord avec toi","I agree with you"],["je ne suis pas d'accord","I disagree"],["c'est vrai, mais…","true, but…"]]}
]},
{w:4,t:"Comparing things",p:[
 {x:"plus…que (more than), moins…que (less than), aussi…que (as…as):", ex:[["le train est plus rapide que le bus","the train is faster than the bus"],["c'est moins cher ici","it's cheaper here"],["il est aussi grand que moi","he's as tall as me"]]},
 {x:"Irregular: bon → meilleur (better), bien → mieux (better, adverb):", ex:[["ce café est meilleur","this coffee is better"],["je parle mieux qu'avant","I speak better than before"]]}
]},
{w:4,t:"Connectors — sound fluent, not robotic",p:[
 {x:"Sprinkle these into every conversation:", ex:[["en fait","actually"],["bien sûr","of course"],["par exemple","for example"],["c'est-à-dire","that is to say"],["cependant","however"],["quand même","still / anyway"],["donc","so"],["alors","well / so"]]},
 {x:"Fillers real French people use (use them while you think!):", ex:[["euh…","uh…"],["bah…","well…"],["tu vois ?","you see?"],["quoi","(end-of-sentence filler)"]]}
]}
],

// ============ Embedded video courses (need internet) ============
videos: {
french: [
 {t:"Language Transfer — Introduction to French",n:"Your grammar backbone — 40 audio lessons. Do 1–2 daily, answer aloud before the student does.",list:"PLeA5t3dWTWvvZln1pJ-Ij8xOmS_3zH-4j",dl:"https://downloads.languagetransfer.org/french/french.zip"},
 {t:"Super Easy French — for beginners",n:"Real slow French from the street, with French + English subtitles. Start in week 2, one video a day.",list:"PLA5UIoabheFMChKPAUUNNEOd7BobVJVoQ"}
],
asl: [
 {t:"ASL University — Dr. Bill Vicars (official playlist)",n:"THE course. Find the lesson number your weekly plan asks for and follow along, signing everything.",list:"PL6akqFwEeSpiLwRFA3ZvuOWMwPXwI7NqA"}
]
},

// ============ ASL numbers reference ============
numbers: [
{n:1,img:"asl/n1.jpg"},
{n:2,img:"asl/n2.jpg"},
{n:3,img:"asl/n3.jpg",note:"ASL 3 = thumb + index + middle (not the European 3!)"},
{n:4,img:"asl/n4.jpg"},
{n:5,d:"Open hand, all five fingers spread, palm toward the person"},
{n:6,img:"asl/n6.jpg",note:"pinky touches thumb"},
{n:7,img:"asl/n7.jpg",note:"ring finger touches thumb"},
{n:8,img:"asl/n8.jpg",note:"middle finger touches thumb"},
{n:9,img:"asl/n9.jpg",note:"index finger touches thumb (like F)"},
{n:10,d:"'A' fist with thumb up, give it a little shake"}
],

// ============ Daily writing prompts (weeks 2-4) ============
writingPrompts: {
2: ["Présente-toi en 5 phrases : nom, âge, ville, ce que tu aimes.",
    "Décris ta famille en 5 phrases simples.",
    "Décris ta maison ou ta chambre (il y a…).",
    "Qu'est-ce que tu vas faire ce week-end ? (je vais + verbe)",
    "Écris un petit dialogue au restaurant (3 échanges).",
    "Décris ton plat préféré et pourquoi tu l'aimes."],
3: ["Qu'est-ce que tu as fait hier ? 6–8 phrases au passé composé.",
    "Raconte ta matinée : je me suis levé…, ensuite…, après…",
    "Décris ta semaine dernière : d'abord, ensuite, enfin.",
    "Raconte un bon souvenir de jeu vidéo (au passé).",
    "Qu'est-ce que tu as mangé aujourd'hui ? Donne des détails.",
    "Écris sur un film ou une série que tu as vu(e)."],
4: ["Donne ton avis : les jeux vidéo, c'est bon ou mauvais ? (je pense que…)",
    "Compare deux villes ou deux jeux (plus… que, moins… que).",
    "Tes projets pour l'année prochaine (je vais…, j'aimerais…).",
    "Pourquoi tu apprends le français ? Explique en 6 phrases.",
    "Décris ta journée idéale (opinions + connecteurs).",
    "Écris un petit texte : ton mois d'août — qu'est-ce que tu as appris ?"]
},

// Conversation prompts to use with Claude, per week
convPrompts: [
{w:1, p:"Practice French with me — week 1 level. Ask me basic questions (name, origin, age, what I do) one at a time, in simple French with English hints. Correct my answers gently and make me repeat corrected versions."},
{w:2, p:"French role-play, week 2 level (A1): you are a waiter in a Paris café / a stranger I ask for directions / a market vendor. Stay in simple French, one line at a time. Correct my mistakes at the end of each scene."},
{w:3, p:"French journal conversation, week 3 level: ask me what I did yesterday and today, in French. Help me use passé composé correctly. Reformulate my broken sentences into natural French and quiz me back on them."},
{w:4, p:"Mock A2 speaking exam in French: interview me (2 min), then a role-play scenario, then ask my opinion on a simple topic. Grade me A1/A2 on vocabulary, grammar, and fluency, with specific feedback."}
]
};

// ============ Bengali glosses (বাংলা) — keyed by the French text ============
APP_DATA.bn = {
// -------- week 1 --------
"bonjour":"হ্যালো / শুভ দিন","bonsoir":"শুভ সন্ধ্যা","salut":"হাই / বাই (ঘরোয়া)","au revoir":"বিদায়",
"à bientôt":"শীঘ্রই দেখা হবে","à demain":"আগামীকাল দেখা হবে","bonne nuit":"শুভ রাত্রি",
"s'il vous plaît":"অনুগ্রহ করে (সম্মানসূচক)","s'il te plaît":"প্লিজ (ঘনিষ্ঠ)","merci beaucoup":"অনেক ধন্যবাদ",
"de rien":"কিছু না / ইউ আর ওয়েলকাম","excusez-moi":"মাফ করবেন","pardon":"দুঃখিত","oui":"হ্যাঁ","non":"না",
"peut-être":"হয়তো","d'accord":"ঠিক আছে","ça va ?":"কেমন আছো?","ça va bien":"ভালো আছি",
"comment allez-vous ?":"আপনি কেমন আছেন?","je m'appelle…":"আমার নাম…","comment tu t'appelles ?":"তোমার নাম কী?",
"enchanté":"পরিচিত হয়ে ভালো লাগলো","je viens de…":"আমি … থেকে এসেছি","j'habite à…":"আমি …-এ থাকি",
"je suis étudiant":"আমি একজন ছাত্র","je parle un peu français":"আমি একটু ফরাসি বলি",
"je ne comprends pas":"আমি বুঝতে পারছি না","pouvez-vous répéter ?":"আবার বলবেন কি?","plus lentement":"আরও ধীরে",
"comment dit-on… ?":"…-কে কী বলে?","qu'est-ce que ça veut dire ?":"এর মানে কী?","je ne sais pas":"আমি জানি না",
"être":"হওয়া","je suis":"আমি (হই/আছি)","tu es":"তুমি (আছো)","il est / elle est":"সে (আছে)",
"nous sommes":"আমরা (আছি)","vous êtes":"আপনি/তোমরা (আছেন)","ils sont":"তারা (আছে)",
"avoir":"থাকা (কারো কিছু)","j'ai":"আমার আছে","tu as":"তোমার আছে","il a / elle a":"তার আছে",
"nous avons":"আমাদের আছে","vous avez":"আপনার আছে","ils ont":"তাদের আছে",
"aller":"যাওয়া","je vais":"আমি যাই / যাচ্ছি","tu vas":"তুমি যাও","il va":"সে যায়","nous allons":"আমরা যাই",
"faire":"করা / বানানো","je fais":"আমি করি","tu fais":"তুমি করো","il fait":"সে করে",
"qui":"কে","quoi":"কী","où":"কোথায়","quand":"কখন","pourquoi":"কেন","comment":"কীভাবে","combien":"কত",
"qu'est-ce que…":"কী… (প্রশ্ন শুরু)","est-ce que…":"(বাক্যকে প্রশ্ন বানায়)","parce que":"কারণ",
"un / une":"একটি (পুং/স্ত্রী)","le / la / les":"নির্দিষ্ট 'টি/টা' (the)","et":"এবং","ou":"অথবা","mais":"কিন্তু",
"avec":"সাথে","sans":"ছাড়া","pour":"জন্য","dans":"ভিতরে","sur":"উপরে","sous":"নিচে",
"ici":"এখানে","là-bas":"ওখানে","aussi":"ও / আরও","très":"খুব","un peu":"একটু","beaucoup":"অনেক",
"zéro":"শূন্য","un, deux, trois":"এক, দুই, তিন","quatre, cinq, six":"চার, পাঁচ, ছয়",
"sept, huit, neuf":"সাত, আট, নয়","dix":"দশ","onze, douze, treize":"এগারো, বারো, তেরো",
"quatorze, quinze, seize":"চৌদ্দ, পনেরো, ষোলো","dix-sept, dix-huit, dix-neuf":"সতেরো, আঠারো, উনিশ",
"vingt":"বিশ","trente":"ত্রিশ","quarante":"চল্লিশ","cinquante":"পঞ্চাশ","soixante":"ষাট",
"soixante-dix":"সত্তর","quatre-vingts":"আশি","quatre-vingt-dix":"নব্বই","cent":"একশো",
"l'homme":"পুরুষ / লোক","la femme":"মহিলা","le garçon":"ছেলে","la fille":"মেয়ে",
"l'ami / l'amie":"বন্ধু","les gens":"লোকজন","aujourd'hui":"আজ","demain":"আগামীকাল","hier":"গতকাল",
"maintenant":"এখন","le matin":"সকাল","l'après-midi":"বিকেল","le soir":"সন্ধ্যা","la nuit":"রাত",
"le jour":"দিন","la semaine":"সপ্তাহ",
// -------- week 2 --------
"manger":"খাওয়া","boire":"পান করা","parler":"কথা বলা","habiter":"বাস করা","travailler":"কাজ করা",
"étudier":"পড়াশোনা করা","aimer":"পছন্দ করা / ভালোবাসা","adorer":"খুব ভালোবাসা","détester":"ঘৃণা করা",
"vouloir":"চাওয়া","je voudrais…":"আমি চাই… (ভদ্রভাবে)","pouvoir":"পারা","je peux":"আমি পারি",
"devoir":"করতে হওয়া","je dois":"আমাকে করতে হবে","acheter":"কেনা","chercher":"খোঁজা","trouver":"খুঁজে পাওয়া",
"donner":"দেওয়া","prendre":"নেওয়া","je prends":"আমি নিই / নেব","regarder":"দেখা","écouter":"শোনা","jouer":"খেলা",
"il y a":"আছে (there is)","je vais + infinitif":"আমি … করতে যাচ্ছি","ne… pas":"না (নেতিবাচক)",
"le pain":"রুটি","l'eau":"পানি","le café":"কফি","le thé":"চা","le lait":"দুধ","le fromage":"পনির",
"la viande":"মাংস","le poulet":"মুরগি","le poisson":"মাছ","les légumes":"সবজি","les fruits":"ফল",
"la pomme":"আপেল","le riz":"ভাত / চাল","l'œuf":"ডিম","le petit-déjeuner":"সকালের নাস্তা",
"le déjeuner":"দুপুরের খাবার","le dîner":"রাতের খাবার","l'addition, s'il vous plaît":"বিলটা দিন, প্লিজ",
"c'est délicieux":"খুব সুস্বাদু","j'ai faim":"আমার খিদে পেয়েছে","j'ai soif":"আমার পিপাসা পেয়েছে",
"la famille":"পরিবার","le père":"বাবা","la mère":"মা","le frère":"ভাই","la sœur":"বোন",
"le fils":"ছেলে (সন্তান)","les parents":"বাবা-মা","les enfants":"বাচ্চারা","le mari":"স্বামী",
"grand / grande":"বড় / লম্বা","petit / petite":"ছোট","bon / bonne":"ভালো","mauvais / mauvaise":"খারাপ",
"beau / belle":"সুন্দর","nouveau / nouvelle":"নতুন","vieux / vieille":"পুরনো / বৃদ্ধ","jeune":"তরুণ",
"facile":"সহজ","difficile":"কঠিন","cher / chère":"দামি","content / contente":"খুশি",
"fatigué / fatiguée":"ক্লান্ত","intéressant":"আকর্ষণীয়",
"la maison":"বাড়ি","l'appartement":"ফ্ল্যাট","la ville":"শহর","la rue":"রাস্তা","le magasin":"দোকান",
"le marché":"বাজার","le restaurant":"রেস্তোরাঁ","l'école":"স্কুল","la gare":"রেলস্টেশন",
"l'aéroport":"বিমানবন্দর","l'hôpital":"হাসপাতাল","la banque":"ব্যাংক",
"à gauche":"বাঁ দিকে","à droite":"ডান দিকে","tout droit":"সোজা","près de":"কাছে","loin de":"দূরে",
"où est… ?":"… কোথায়?","ça coûte combien ?":"এটার দাম কত?","c'est trop cher":"খুব বেশি দাম","l'argent":"টাকা",
"lundi":"সোমবার","mardi":"মঙ্গলবার","mercredi":"বুধবার","jeudi":"বৃহস্পতিবার","vendredi":"শুক্রবার",
"samedi":"শনিবার","dimanche":"রবিবার","le week-end":"সাপ্তাহিক ছুটি","quelle heure est-il ?":"কয়টা বাজে?",
"il est trois heures":"তিনটা বাজে",
// -------- week 3 --------
"j'ai mangé":"আমি খেয়েছি","j'ai parlé":"আমি বলেছি","j'ai fait":"আমি করেছি","j'ai vu":"আমি দেখেছি",
"j'ai pris":"আমি নিয়েছি","j'ai eu":"আমার ছিল","j'ai été":"আমি ছিলাম","je suis allé(e)":"আমি গিয়েছিলাম",
"je suis arrivé(e)":"আমি পৌঁছেছি","je suis parti(e)":"আমি চলে গেছি","je suis resté(e)":"আমি থেকেছি",
"je me suis levé(e)":"আমি (ঘুম থেকে) উঠেছি","hier soir":"গতরাতে","la semaine dernière":"গত সপ্তাহে",
"il y a deux jours":"দুই দিন আগে","déjà":"ইতিমধ্যে","pas encore":"এখনো না","ensuite":"তারপর",
"après":"পরে","avant":"আগে","pendant":"চলাকালীন","toujours":"সবসময়","souvent":"প্রায়ই",
"parfois":"মাঝে মাঝে","jamais":"কখনো না",
"se lever":"ওঠা","se réveiller":"ঘুম থেকে জাগা","se doucher":"গোসল করা","s'habiller":"পোশাক পরা",
"se coucher":"ঘুমাতে যাওয়া","dormir":"ঘুমানো","je dors":"আমি ঘুমাই","cuisiner":"রান্না করা",
"nettoyer":"পরিষ্কার করা","se reposer":"বিশ্রাম নেওয়া","sortir":"বাইরে যাওয়া","rentrer":"বাড়ি ফেরা",
"lire":"পড়া","je lis":"আমি পড়ি","écrire":"লেখা","j'écris":"আমি লিখি","apprendre":"শেখা",
"j'apprends le français":"আমি ফরাসি শিখছি",
"quel temps fait-il ?":"আবহাওয়া কেমন?","il fait beau":"আবহাওয়া ভালো","il fait chaud":"গরম পড়েছে",
"il fait froid":"ঠান্ডা পড়েছে","il pleut":"বৃষ্টি হচ্ছে","il neige":"তুষার পড়ছে","le soleil":"সূর্য",
"la pluie":"বৃষ্টি","le vent":"বাতাস",
"la tête":"মাথা","la main":"হাত","les yeux":"চোখ","la bouche":"মুখ","le pied":"পা (পাতা)",
"j'ai mal à la tête":"আমার মাথা ব্যথা করছে","je suis malade":"আমি অসুস্থ","le médecin":"ডাক্তার",
"la pharmacie":"ফার্মেসি","aider":"সাহায্য করা","pouvez-vous m'aider ?":"আমাকে সাহায্য করবেন?",
"attendre":"অপেক্ষা করা","commencer":"শুরু করা","finir":"শেষ করা","choisir":"বেছে নেওয়া",
"venir":"আসা","je viens":"আমি আসি","savoir":"জানা (তথ্য)","connaître":"চেনা (মানুষ/জায়গা)",
"dire":"বলা","voir":"দেখা","donc":"তাই","alors":"তাহলে / তো","puis":"তারপর",
"quelque chose":"কিছু","quelqu'un":"কেউ","tout / tous":"সব","rien":"কিছুই না",
// -------- week 4 --------
"je pense que…":"আমি মনে করি…","à mon avis":"আমার মতে","je crois que…":"আমার বিশ্বাস…",
"je suis d'accord":"আমি একমত","je ne suis pas d'accord":"আমি একমত নই","c'est vrai":"এটা সত্যি",
"c'est faux":"এটা ভুল","j'espère que…":"আমি আশা করি…","il me semble que…":"আমার মনে হয়…",
"le week-end prochain":"আগামী উইকএন্ডে","l'année prochaine":"আগামী বছর","je vais voyager":"আমি ভ্রমণ করব",
"je vais essayer":"আমি চেষ্টা করব","j'aimerais…":"আমার ইচ্ছা…","je veux devenir…":"আমি … হতে চাই",
"heureux / heureuse":"সুখী","triste":"দুঃখী","en colère":"রাগান্বিত","surpris / surprise":"অবাক",
"inquiet / inquiète":"চিন্তিত","j'ai peur de…":"আমি … ভয় পাই","ça me plaît":"এটা আমার ভালো লাগে",
"ça m'énerve":"এটা আমাকে বিরক্ত করে",
"le voyage":"ভ্রমণ","les vacances":"ছুটি","le billet":"টিকিট","le train":"ট্রেন","l'avion":"বিমান",
"la voiture":"গাড়ি","le vélo":"সাইকেল","le bus":"বাস","l'hôtel":"হোটেল","la plage":"সৈকত",
"la montagne":"পাহাড়","le pays":"দেশ","l'étranger":"বিদেশ","réserver":"বুক করা","visiter":"ঘুরে দেখা",
"le travail":"কাজ / চাকরি","le bureau":"অফিস / ডেস্ক","l'ordinateur":"কম্পিউটার","le téléphone":"ফোন",
"envoyer un message":"মেসেজ পাঠানো","le projet":"প্রজেক্ট","le jeu vidéo":"ভিডিও গেম","la musique":"গান",
"le film":"সিনেমা","le livre":"বই","le sport":"খেলাধুলা","faire du sport":"খেলাধুলা করা","la langue":"ভাষা",
"la langue des signes":"ইশারা ভাষা",
"cependant":"তবে","par exemple":"যেমন","c'est-à-dire":"অর্থাৎ","en fait":"আসলে","bien sûr":"অবশ্যই",
"peut-être que…":"হয়তো…","si":"যদি","quand même":"তবুও","d'abord":"প্রথমে","enfin":"অবশেষে",
"mieux":"আরও ভালো","pire":"আরও খারাপ","plus… que":"…-এর চেয়ে বেশি","moins… que":"…-এর চেয়ে কম",
"le meilleur":"সেরা","trop":"অতিরিক্ত","assez":"যথেষ্ট","presque":"প্রায়","vraiment":"সত্যিই",
"peu à peu":"ধীরে ধীরে",
// -------- picture words not already above --------
"la banane":"কলা","l'orange":"কমলা","la pizza":"পিৎজা","le chocolat":"চকলেট","le gâteau":"কেক",
"la salade":"সালাদ","la soupe":"স্যুপ","le beurre":"মাখন","le sucre":"চিনি","le sel":"লবণ",
"le vin":"ওয়াইন","le jus":"জুস","le chat":"বিড়াল","le chien":"কুকুর","l'oiseau":"পাখি",
"le cheval":"ঘোড়া","la vache":"গরু","la souris":"ইঁদুর","le lapin":"খরগোশ","le lion":"সিংহ",
"l'éléphant":"হাতি","le serpent":"সাপ","la clé":"চাবি","la porte":"দরজা","la fenêtre":"জানালা",
"le lit":"বিছানা","la chaise":"চেয়ার","l'assiette":"প্লেট","la cuillère":"চামচ","le couteau":"ছুরি",
"la fourchette":"কাঁটাচামচ","la chemise":"শার্ট","le pantalon":"প্যান্ট","les chaussures":"জুতা",
"le sac":"ব্যাগ","la montre":"ঘড়ি","les lunettes":"চশমা","le crayon":"পেন্সিল","le papier":"কাগজ",
"la télévision":"টেলিভিশন","l'appareil photo":"ক্যামেরা","l'immeuble":"দালান","l'église":"গির্জা",
"le pont":"সেতু","la mer":"সমুদ্র","l'arbre":"গাছ","la fleur":"ফুল","le taxi":"ট্যাক্সি",
"le bateau":"নৌকা","le nez":"নাক","l'oreille":"কান","la jambe":"পা","le bras":"বাহু","le cœur":"হৃদয়",
"la lune":"চাঁদ","l'étoile":"তারা","la neige":"তুষার","le nuage":"মেঘ","le feu":"আগুন",
"rouge":"লাল","bleu":"নীল","vert":"সবুজ","jaune":"হলুদ","noir":"কালো","blanc":"সাদা",
"orange":"কমলা রঙ","violet":"বেগুনি","marron":"বাদামি","rose":"গোলাপি",
"le bébé":"শিশু","le grand-père":"দাদা / নানা","la grand-mère":"দাদি / নানি","le policier":"পুলিশ",
// -------- phrases --------
"Je m'appelle Psy et j'apprends le français.":"আমার নাম সাই এবং আমি ফরাসি শিখছি।",
"Je viens du Bangladesh.":"আমি বাংলাদেশ থেকে এসেছি।",
"J'ai vingt ans.":"আমার বয়স বিশ বছর।",
"Qu'est-ce que tu fais dans la vie ?":"তুমি কী করো (পেশা)?",
"Je suis désolé, je ne parle pas bien français.":"দুঃখিত, আমি ভালো ফরাসি বলতে পারি না।",
"Vous pouvez parler plus lentement, s'il vous plaît ?":"একটু ধীরে বলবেন, প্লিজ?",
"Je voudrais un café, s'il vous plaît.":"আমি একটা কফি চাই, প্লিজ।",
"Est-ce que vous avez une table pour deux ?":"দুজনের জন্য টেবিল আছে কি?",
"Où sont les toilettes ?":"টয়লেট কোথায়?",
"Je cherche la gare.":"আমি রেলস্টেশন খুঁজছি।",
"C'est combien, ça ?":"এটা কত দাম?",
"Je vais prendre le poulet avec du riz.":"আমি ভাতের সাথে মুরগি নেব।",
"Ma famille habite loin d'ici.":"আমার পরিবার এখান থেকে দূরে থাকে।",
"Ce week-end, je vais jouer aux jeux vidéo.":"এই উইকএন্ডে আমি ভিডিও গেম খেলব।",
"Hier, j'ai étudié le français pendant deux heures.":"গতকাল আমি দুই ঘণ্টা ফরাসি পড়েছি।",
"Ce matin, je me suis levé à huit heures.":"আজ সকালে আমি আটটায় উঠেছি।",
"Je suis allé au marché et j'ai acheté des fruits.":"আমি বাজারে গিয়ে ফল কিনেছি।",
"Qu'est-ce que tu as fait hier soir ?":"গতরাতে তুমি কী করেছিলে?",
"Je n'ai pas encore fini mon projet.":"আমি এখনো আমার প্রজেক্ট শেষ করিনি।",
"Il a plu toute la journée.":"সারাদিন বৃষ্টি হয়েছে।",
"J'apprends aussi la langue des signes américaine.":"আমি আমেরিকান ইশারা ভাষাও শিখছি।",
"À mon avis, c'est une bonne idée.":"আমার মতে, এটা ভালো আইডিয়া।",
"Je pense que le français est plus facile qu'avant.":"আমার মনে হয় ফরাসি আগের চেয়ে সহজ।",
"L'année prochaine, j'aimerais visiter la France.":"আগামী বছর আমি ফ্রান্স ঘুরতে চাই।",
"D'abord je travaille, ensuite je joue, enfin je dors.":"প্রথমে কাজ, তারপর খেলা, শেষে ঘুম।",
"En fait, j'ai commencé il y a seulement un mois.":"আসলে, আমি মাত্র এক মাস আগে শুরু করেছি।",
"Je parle français mieux qu'avant, peu à peu.":"আমি আগের চেয়ে ভালো ফরাসি বলি, ধীরে ধীরে।",
"Si tu veux, on peut parler en français.":"তুমি চাইলে আমরা ফরাসিতে কথা বলতে পারি।"
};
